modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
logoFile="logo.png"
credits=""
authors=""
description='''Autopilot towers, radar coverage, and route guidance for Immersive Aircraft.'''

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="[21.1.133,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="immersive_aircraft"
mandatory=true
versionRange="[1.2.2,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="immersive_autopilot.mixins.json"
